### ISSUE TITLE
Sorties time history pour le cas CAS_plaque_demi_euler_Y_depot_Gaussian

### ISSUE THREAD

**Issue by spraulm** [cea-hpc/MaHyCo#56]
Le cas CAS_plaque_demi_euler_Y_depot_Gaussian n'a pas de sorties time history.

Seul le GlobalTime est sorti sur la première itération. 

Il reste à comprendre pourquoi aucun autre fichier n'est sorti.

Le jeu de données semble correct, comparé à la rubrique time-history des autres cas tests.

**Comment by spraulm** [comment]
Je vais contacter Alexandre pour tenter de comprendre

**Comment by AlexlHer** [comment]
Le blocage des sorties TimeHistory est lié à la ligne ci-dessous : 
https://github.com/cea-hpc/MaHyCo/blob/a7f14a2f03972909770bf737c257b87cde1e8b0f/NONREGRESSION/CAS_plaque_demi_euler_Y_depot_Gaussian/Donnees.arc#L33

Pour contrôler la période de sortie du post processing, en plus de celle du TimeHistory, tu peux utiliser l'option `output-period` : 
```xml
<output-history-period>1</output-history-period>
<output-period>500</output-period>
```

**Comment by spraulm** [comment]
Merci Alexandre pour ta réponse rapide. Effectivement, je n'avais pas vu cette ligne. Je vais corriger ça.

**Comment by spraulm** [comment]
Résolu via https://github.com/cea-hpc/MaHyCo/pull/58
